apiVersion: v1
kind: Service
metadata:
  name: release-manager-backend-service
  namespace: release-manager
  labels:
    app: release-manager-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: release-manager-backend
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
